// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA20BKP45PrmD3w1JIHcG6Xq5X4Kgl2sUU',
    appId: '1:393328283698:web:074be7fb1c8967d21f6c2b',
    messagingSenderId: '393328283698',
    projectId: 'gametracker-a834b',
    authDomain: 'gametracker-a834b.firebaseapp.com',
    storageBucket: 'gametracker-a834b.firebasestorage.app',
    measurementId: 'G-KBGW7G848D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5S9P-pRbp80AlkfJ28kVgHZNqu18rg7s',
    appId: '1:393328283698:android:36f5135ea09c90601f6c2b',
    messagingSenderId: '393328283698',
    projectId: 'gametracker-a834b',
    storageBucket: 'gametracker-a834b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGCIiRpHZ_LxLFwZdqleBCpLfBB8Tjjgo',
    appId: '1:393328283698:ios:3ca176e0b3083b211f6c2b',
    messagingSenderId: '393328283698',
    projectId: 'gametracker-a834b',
    storageBucket: 'gametracker-a834b.firebasestorage.app',
    iosBundleId: 'com.gametracker.pokerTracker',
  );
}
